# Per-platform sha256 hashes for prebuilt release tarballs published to
# https://github.com/lqdev/podcast-tui/releases.
#
# This file is regenerated by `scripts/update-flake-hashes.sh` after each tag.
# A platform mapped to `null` means no prebuilt binary exists for this version
# on that platform; the flake will fall through to the source build.
#
# Format: { version = "X.Y.Z"; hashes = { "<system>" = "sha256-..." or null; ... }; }
{
  version = "1.14.0";
  hashes = {
    "aarch64-linux" = "sha256-PWR53Iuudw1SiWlFhdUUp75z/GvFZo21ElH6FtB2sy8=";
    "x86_64-linux"  = "sha256-tCGkXgF1T0p89ONc4YywB7DjrLTnHmTaBoO1oB/8/zY=";
  };
}
