# Per-platform sha256 hashes for prebuilt release tarballs published to
# https://github.com/lqdev/podcast-tui/releases.
#
# This file is regenerated by `scripts/update-flake-hashes.sh` after each tag.
# A platform mapped to `null` means no prebuilt binary exists for this version
# on that platform; the flake will fall through to the source build.
#
# Format: { version = "X.Y.Z"; hashes = { "<system>" = "sha256-..." or null; ... }; }
{
  version = "1.15.0";
  hashes = {
    "aarch64-linux" = "sha256-HgfM23AeBDU159b9jL2aQqBeGFDmAcMD45NulZ2wqYc=";
    "x86_64-linux"  = "sha256-AN/6U9S2xWurENcdiQ4GH5ju9tPaYGOzf4OofbKoPM8=";
  };
}
