name: Bug Report
description: Report a bug in the podcast TUI application
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out this template to help us reproduce and fix the issue.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low - Minor inconvenience
        - Medium - Affects functionality but has workarounds
        - High - Major functionality broken
        - Critical - Application unusable/crashes
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: What part of the application is affected?
      options:
        - UI/Navigation - User interface and keyboard navigation
        - Audio Playback - Audio playback functionality
        - Downloads - Episode downloading
        - RSS/Feeds - Feed parsing and subscription management
        - Storage/Config - Data persistence and configuration
        - Cross-platform - Platform-specific issues
        - Performance - Speed or resource issues
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "When I do X, Y happens but I expected Z..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Press key '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide details about your environment
      placeholder: |
        - OS: [e.g., Windows 11, Ubuntu 22.04]
        - Terminal: [e.g., Windows Terminal, GNOME Terminal]
        - Rust version: [e.g., 1.75.0]
        - Application version: [e.g., 1.0.0-mvp]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Any relevant error messages or logs (please use code blocks)
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional context, screenshots, or information that might be helpful