# Cargo configuration for cross-compilation
# This file configures linkers and build settings for various target platforms

# Note: Linker configuration is handled by cargo-zigbuild when invoked
# For native builds, use regular cargo which will use the system linker

# Build settings
[build]
# Increase parallelism for faster builds
jobs = 4

# Profile settings for optimized release builds
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

# Smaller binary size profile (optional)
[profile.release-small]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
