#!/usr/bin/env bash
# update-flake-hashes.sh — regenerate nix/release-hashes.nix for a given tag.
#
# Fetches the published .sha256 sidecar for each prebuilt Linux tarball
# attached to the GitHub Release, converts to SRI form, and writes a fresh
# nix/release-hashes.nix. Platforms missing from the release are emitted as
# `null` so the flake falls through to the source build.
#
# Usage:
#   scripts/update-flake-hashes.sh v1.13.0
#
# Requirements: curl, nix (for `nix hash convert`).
#
# Intended to be invoked from CI (.github/workflows/release.yml) immediately
# after `create-release` succeeds, opening a PR against `main`.

set -euo pipefail

TAG="${1:-}"
if [[ -z "$TAG" ]]; then
  echo "usage: $0 <tag>   (e.g. v1.13.0)" >&2
  exit 64
fi

VERSION="${TAG#v}"
REPO="lqdev/podcast-tui"
BASE="https://github.com/${REPO}/releases/download/${TAG}"
OUT="nix/release-hashes.nix"

# system tag -> release-filename platform suffix
declare -A PLATFORMS=(
  [x86_64-linux]=linux-x86_64
  [aarch64-linux]=linux-aarch64
)

declare -A HASHES=()

for system in "${!PLATFORMS[@]}"; do
  suffix="${PLATFORMS[$system]}"
  url="${BASE}/podcast-tui-${TAG}-${suffix}.tar.gz.sha256"
  echo ">> fetching $url" >&2
  if hex=$(curl -fsSL "$url" 2>/dev/null | awk '{print $1}'); then
    if [[ -n "$hex" ]]; then
      sri=$(nix hash convert --from base16 --to sri --hash-algo sha256 "$hex")
      HASHES[$system]="$sri"
      echo "   $system -> $sri" >&2
      continue
    fi
  fi
  echo "   $system -> (not published, will use source build)" >&2
  HASHES[$system]=""
done

# Emit fresh release-hashes.nix.
{
  cat <<HEADER
# Per-platform sha256 hashes for prebuilt release tarballs published to
# https://github.com/lqdev/podcast-tui/releases.
#
# This file is regenerated by \`scripts/update-flake-hashes.sh\` after each tag.
# A platform mapped to \`null\` means no prebuilt binary exists for this version
# on that platform; the flake will fall through to the source build.
#
# Format: { version = "X.Y.Z"; hashes = { "<system>" = "sha256-..." or null; ... }; }
{
  version = "${VERSION}";
  hashes = {
HEADER

  # Sort keys for stable diffs.
  for system in $(printf '%s\n' "${!HASHES[@]}" | sort); do
    sri="${HASHES[$system]}"
    # Compute padding so values align regardless of system-name length
    # (e.g. "x86_64-linux" gets 1 extra space vs "aarch64-linux").
    pad=""
    for ((i=${#system}; i<13; i++)); do pad="$pad "; done
    if [[ -z "$sri" ]]; then
      printf '    "%s"%s = null;\n' "$system" "$pad"
    else
      printf '    "%s"%s = "%s";\n' "$system" "$pad" "$sri"
    fi
  done

  cat <<FOOTER
  };
}
FOOTER
} > "$OUT"

echo ">> wrote $OUT" >&2
