use crate::storage::{EpisodeId, PodcastId};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Unique identifier for playlists.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PlaylistId(pub Uuid);

impl PlaylistId {
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }

    pub fn from_string(s: &str) -> Result<Self, uuid::Error> {
        Ok(Self(Uuid::parse_str(s)?))
    }

    /// Create a deterministic ID for auto-generated playlists.
    pub fn from_name(name: &str) -> Self {
        use std::collections::hash_map::DefaultHasher;
        use std::hash::{Hash, Hasher};

        let mut hasher = DefaultHasher::new();
        name.hash(&mut hasher);
        let hash = hasher.finish();
        Self(Uuid::from_u64_pair(hash, hash))
    }
}

impl Default for PlaylistId {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Display for PlaylistId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// A playlist of podcast episodes.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Playlist {
    pub id: PlaylistId,
    pub name: String,
    pub description: Option<String>,
    pub playlist_type: PlaylistType,
    pub episodes: Vec<PlaylistEpisode>,
    pub created: DateTime<Utc>,
    pub last_updated: DateTime<Utc>,
}

/// Distinguishes user-created from auto-generated playlists.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PlaylistType {
    User,
    AutoGenerated {
        generator: AutoPlaylistKind,
        refresh_policy: RefreshPolicy,
        last_refreshed: Option<DateTime<Utc>>,
    },
}

/// Kinds of auto-generated playlists.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AutoPlaylistKind {
    Today,
}

/// When to refresh auto-generated playlists.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum RefreshPolicy {
    Daily,
    OnLaunch,
    Manual,
}

/// An episode reference within a playlist.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlaylistEpisode {
    pub podcast_id: PodcastId,
    pub episode_id: EpisodeId,
    #[serde(default)]
    pub episode_title: Option<String>,
    pub added_at: DateTime<Utc>,
    pub order: usize,
    /// Whether the audio file has been copied to the playlist directory.
    pub file_synced: bool,
    /// Filename inside the playlist audio directory.
    pub filename: Option<String>,
}
